### ISSUE TITLE
vault_payment_token duplicate entry

### ISSUE THREAD

**Issue by yrudiuk** [subscribepro/subscribepro-magento2-ext#77] opened 2018-07-23 09:15 UTC
Hello,

We are having next error on 3 of our 2.1.X projects when placing an order:
Exception message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'subscribe_pro-126837-3525036' for key 'UNQ_54DCE14AEAEA03B587F9EF723EB10A10', query was: INSERT INTO `vault_payment_token`

As the result, we have order duplicates in SubscribePro, but not in Magento.
Customers are getting charged twice.

This is happening when website is under load.

Unfortunately, we can't upgrade to the latest SP version as it requires Magento 2.2.X version.
Also, we can't determine the root cause of this issue for now, so not sure if this is Magento or SubscribePro.

Was this error noticed by your team previously?

Thanks!

**Comment by eugene-shab** [comment] 2023-11-28 10:37
I have doubts that this task is relevant, but in any case, I think that the problem is related to the fact that on overload, some of the data from Magento is lost. I would recommend that the client should install services that monitor activity and data integrity, such as Blackfire and Newrelic.

If the problem is still relevant, then I will install the old version of Magento 2.1.X and at the very least, I require steps to reproduce this behaviour.

 @garthbrantley   What do you think about it?

**Comment by garthbrantley** [comment] 2023-11-28 23:20
Closing because no longer relevant.

**Closed by garthbrantley** 2023-11-28 23:20 UTC
Labels: payments
