### ISSUE TITLE
My Subscriptions | Virtual Product | Unable to update subscription

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/subscribepro-magento2-ext#186] opened 2023-08-18 15:20 UTC
PR: #46

When attempting to update a subscription with the `Native` my subscription widget on a subscription for a virtual product it fails with a 409 and `Please enter a first name. Field: firstName Value:`

This is because an empty shipping address array is being sent like the following

```
        "shipping_address": [
            
        ],
```

When virtual product shipping address should not be sent.

**Comment by czettnersandor** [comment] 2023-08-23 16:36
@chrismshea Please describe what Native means. I just tested editing subscriptions for virtual products multiple times, and I can change periods, can restart and stop subscriptions in the customer's My Account pages

**Comment by chrismshea** [comment] 2023-08-23 16:43
@czettnersandor native meaning that in configuration you are **NOT** setup to use the hosted my subscriptions widget.  In Swarming > Subscribe Pro > Advanced: set Enable Hosted My Subscriptions Page = No

**Comment by czettnersandor** [comment] 2023-08-24 11:24
@chrismshea Thanks. I can reproduce the error, but not getting the same error message. The reasonPhrase it "Conflict" and the error sent back to the frontend is `{"message":"An error occurred while updating interval."}`

I trust the issue you described is because of the empty shipping_address array, so I'm changing that

**Comment by czettnersandor** [comment] 2023-08-24 12:07
Fixed in https://github.com/subscribepro/subscribepro-php/pull/46

**Closed** 2023-08-25 17:30 UTC
