### ISSUE TITLE
Tiered pricing and subscription discounts in M2 Extension

### ISSUE THREAD

**Issue by imkingdavid** [subscribepro/subscribepro-magento2-ext#14] opened 2017-03-07 22:07 UTC
"We are noticing an issue with Magento 2.1.3 Enterprise and Subscript Pro 1.0.7.

A subscription product setup in Magento with a tier price will not reflect any subscription discount amount configured in Subscribe Pro on the PLP or PDP. The cart and mini cart will reflect discount percentages. On the PLP and PDP, only the tier price is reflected."

**Comment by garthbrantley** [comment] 2017-03-22 17:43
Duplicate of #20

**Closed by garthbrantley** 2017-03-22 17:43 UTC
